# Generated by Django 3.0.3 on 2020-02-11 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancelled',
        ),
    ]
