# Generated by Django 3.0.3 on 2020-02-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_booking_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(default=123123123),
            preserve_default=False,
        ),
    ]
