# Generated by Django 3.0.3 on 2020-02-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
